name: Ormolu CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v15
        with:
            version: "0.7.2.0"